### ISSUE TITLE
Recommended Node version?

### ISSUE THREAD

**Issue by bamtan** [TinyMan/node-jeanne#11]
Hi, I'd love to run this project but cannot get past errors once running `npm i`.

I've tried with both Node v10.15.1 and v8.15.0, with npm 6.4.1.

Debian 9 / Ubuntu 16.04

Thanks

**Comment by TinyMan** [comment]
What are your errors ?

I'm running with node v8.15 and npm 6.8.0 (previously 5.7.1) on Raspbian 8 with no problem.

**Comment by bamtan** [comment]
Update npm and was able to get paste `npm -i` without any red errors, only warnings. When running `node index.js`

```bash
$ node index.js
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
[../deps/mpg123/src/output/alsa.c:165] error: cannot open device default
node: pcm_params.c:2290: snd_pcm_hw_refine: Assertion `pcm && params' failed.
Aborted
```
I have the following alsa packages installed: `alsabat, alsaloop, alsamixer, alsatplg, alsaucm`

Running `node index.js with sudo:
```bash
$ sudo node index.js
/home/bam/node-jeanne/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: The module '/home/bam/node-jeanne/node_modules/jitterbuffer/build/Release/node-jitterbuffer.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 67. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:779:18)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at bindings (/home/bam/node-jeanne/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/bam/node-jeanne/node_modules/jitterbuffer/index.js:2:39)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
```

**Comment by bamtan** [comment]
I was able to resolve this issue by creating a dummy sound card driver following these steps:

Create a file called "myalias.conf" in /etc/modprobe.d/
```
cd /etc/modprobe.d/
sudo touch myalias.conf
```

Enter the lines form the guide
```
alias char-major-116 snd
alias snd-card-0 snd-dummy
```
Save that file and close it.

Finally, load this module
```
sudo modprobe snd-dummy
```

Reference: https://www.reddit.com/r/linux4noobs/comments/2m77g1/help_a_noob_create_a_dummy_sound_card_driver/
https://www.alsa-project.org/main/index.php/Matrix:Module-dummy (outdated)
